name: coclico
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - conda-forge:pdal==2.5.*
  - conda-forge:python-pdal==3.2.*
  - requests
  - pytest
  # linting (cf https://dev.to/m1yag1/how-to-setup-your-project-with-pre-commit-black-and-flake8-183k)
  - black
  - flake8
  - pre-commit
