mpap0:
  weights:
    "1": 0.5
    "2": 7
    "3_4_5": 4
    "6": 4
    "9": 1
    "17": 3
    "64": 2
  notes:
    ref_count_threshold: 1000
    under_threshold:
      # tuple for the first point with the lowest metric value
      min_point:
        metric: 20  # absolute diff
        note: 1
      # tuple for the first point with the highest metric value
      max_point:
        metric: 100  # absolute diff
        note: 0
    above_threshold:
      # tuple for the first point with the lowest metric value
      min_point:
        metric: 0  # relative diff
        note: 1
      # tuple for the first point with the highest metric value
      max_point:
        metric: 0.1  # relative diff
        note: 0


mpla0:
  weights:
    "2": 28
    "4_5": 16
    "6": 16
    "9": 4
    "17": 12

malt0:
  weights:
    "2": 56
    "3_4_5": 16
    "6": 16
