name: cicd_light

on:
  # Run tests for non-draft pull request on dev
  pull_request:
    branches:
      - main


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      # See https://github.com/marketplace/actions/setup-micromamba
      - name: install
        uses: mamba-org/setup-micromamba@v1.4.3
        with:
          environment-file: environment.yml
          environment-name: coclico  # activate the environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true

      - name: test
        shell: micromamba-shell {0}
        run: python -m pytest ./test -s --log-cli-level DEBUG

